# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataBaseView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataBaseView(object):
    def setupUi(self, DataBaseView):
        """
        Настраивает пользовательский интерфейс для окна просмотра базы данных.

        Действия:
        - Устанавливает свойства окна, такие как название, размер, шрифт и иконка.
        - Создает и настраивает виджеты, такие как метки, кнопки, таблицу и выпадающий список.
        - Устанавливает текст, шрифты, размеры и стили для виджетов.
        """
        DataBaseView.setObjectName("DataBaseView")
        DataBaseView.resize(1400, 800)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        DataBaseView.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files_for_demoexam/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DataBaseView.setWindowIcon(icon)
        self.application_name = QtWidgets.QLabel(DataBaseView)
        self.application_name.setGeometry(QtCore.QRect(340, 90, 721, 81))
        font_big = QtGui.QFont()
        font_big.setFamily("Comic Sans MS")
        font_big.setPointSize(48)
        self.application_name.setFont(font_big)
        self.application_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.application_name.setObjectName("application_name")
        self.app_icon = QtWidgets.QLabel(DataBaseView)
        self.app_icon.setGeometry(QtCore.QRect(280, 100, 60, 60))
        self.app_icon.setText("")
        self.app_icon.setPixmap(QtGui.QPixmap("files_for_demoexam/logo.png"))
        self.app_icon.setScaledContents(True)
        self.app_icon.setObjectName("app_icon")
        self.go_back = QtWidgets.QPushButton(DataBaseView)
        self.go_back.setGeometry(QtCore.QRect(20, 710, 221, 51))
        font.setBold(True)
        font.setWeight(75)
        self.go_back.setFont(font)
        self.go_back.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.go_back.setObjectName("go_back")
        self.try_to_connect_db = QtWidgets.QPushButton(DataBaseView)
        self.try_to_connect_db.setGeometry(QtCore.QRect(560, 180, 221, 51))
        self.try_to_connect_db.setFont(font)
        self.try_to_connect_db.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.try_to_connect_db.setObjectName("try_to_connect_db")
        self.db_viewer = QtWidgets.QTableView(DataBaseView)
        self.db_viewer.setGeometry(QtCore.QRect(240, 240, 861, 451))
        self.db_viewer.setObjectName("db_viewer")
        self.choose_db_table = QtWidgets.QComboBox(DataBaseView)
        self.choose_db_table.setGeometry(QtCore.QRect(240, 210, 281, 22))
        self.choose_db_table.setFont(font)
        self.choose_db_table.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.choose_db_table.setObjectName("choose_db_table")
        self.choose_label = QtWidgets.QLabel(DataBaseView)
        self.choose_label.setGeometry(QtCore.QRect(240, 180, 281, 16))
        self.choose_label.setFont(font)
        self.choose_label.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.choose_label.setObjectName("choose_label")

        self.retranslateUi(DataBaseView)
        QtCore.QMetaObject.connectSlotsByName(DataBaseView)

    def retranslateUi(self, DataBaseView):
        """
        Устанавливает текст для виджетов в окне просмотра базы данных.

        Действия:
        - Устанавливает заголовок окна и текст для меток и кнопок.
        """
        _translate = QtCore.QCoreApplication.translate
        DataBaseView.setWindowTitle(_translate("DataBaseView", "Просмотр базы данных"))
        self.application_name.setText(_translate("DataBaseView", "Название Приложения"))
        self.go_back.setText(_translate("DataBaseView", "Вернуться в меню"))
        self.try_to_connect_db.setText(_translate("DataBaseView", "Подкючиться к базе"))
        self.choose_label.setText(_translate("DataBaseView", "Выберите таблицу для просмотра:"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     DataBaseView = QtWidgets.QWidget()
#     ui = Ui_DataBaseView()
#     ui.setupUi(DataBaseView)
#     DataBaseView.show()
#     sys.exit(app.exec_())
