# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        """
        Настраивает пользовательский интерфейс для главного меню приложения.

        Параметры:
        MainMenu (QMainWindow): Главное окно приложения.

        Действия:
        - Устанавливает свойства главного окна, такие как название, размер, шрифт и иконка.
        - Создает и настраивает виджеты, такие как метки, кнопки и центральный виджет.
        - Устанавливает текст, шрифты, размеры и стили для виджетов.
        """
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1400, 800)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        MainMenu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files_for_demoexam/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainMenu.setWindowIcon(icon)
        MainMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.application_name = QtWidgets.QLabel(self.centralwidget)
        self.application_name.setGeometry(QtCore.QRect(340, 90, 721, 81))
        font_big = QtGui.QFont()
        font_big.setFamily("Comic Sans MS")
        font_big.setPointSize(48)
        self.application_name.setFont(font_big)
        self.application_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.application_name.setObjectName("application_name")
        self.go_to_database = QtWidgets.QPushButton(self.centralwidget)
        self.go_to_database.setGeometry(QtCore.QRect(550, 240, 280, 50))
        font.setBold(True)
        font.setWeight(75)
        self.go_to_database.setFont(font)
        self.go_to_database.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.go_to_database.setObjectName("go_to_database")
        self.add_element_to_database = QtWidgets.QPushButton(self.centralwidget)
        self.add_element_to_database.setGeometry(QtCore.QRect(550, 310, 280, 50))
        self.add_element_to_database.setFont(font)
        self.add_element_to_database.setStyleSheet("color: rgb(73, 140, 81);\\n")
        self.add_element_to_database.setObjectName("add_element_to_database")
        self.add_element_to_database.setEnabled(False)
        self.update_database = QtWidgets.QPushButton(self.centralwidget)
        self.update_database.setGeometry(QtCore.QRect(550, 380, 280, 50))
        self.update_database.setFont(font)
        self.update_database.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.update_database.setObjectName("update_database")
        self.update_database.setEnabled(False)
        self.delete_element_of_database = QtWidgets.QPushButton(self.centralwidget)
        self.delete_element_of_database.setGeometry(QtCore.QRect(550, 450, 280, 50))
        self.delete_element_of_database.setFont(font)
        self.delete_element_of_database.setStyleSheet("color: rgb(73, 140, 81);\n"
"")
        self.delete_element_of_database.setObjectName("delete_element_of_database")
        self.delete_element_of_database.setEnabled(False)
        self.exit_application = QtWidgets.QPushButton(self.centralwidget)
        self.exit_application.setGeometry(QtCore.QRect(1170, 740, 221, 51))
        self.exit_application.setFont(font)
        self.exit_application.setStyleSheet("")
        self.exit_application.setObjectName("exit_application")
        self.app_icon = QtWidgets.QLabel(self.centralwidget)
        self.app_icon.setGeometry(QtCore.QRect(280, 100, 60, 60))
        self.app_icon.setText("")
        self.app_icon.setPixmap(QtGui.QPixmap("files_for_demoexam/logo.png"))
        self.app_icon.setScaledContents(True)
        self.app_icon.setObjectName("app_icon")
        MainMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        """
        Устанавливает текст для виджетов в главном меню.

        Параметры:
        MainMenu (QMainWindow): Главное окно приложения.

        Действия:
        - Устанавливает заголовок окна и текст для меток и кнопок.
        """
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Главное меню"))
        self.application_name.setText(_translate("MainMenu", "Название Приложения"))
        self.go_to_database.setText(_translate("MainMenu", "База данных"))
        self.add_element_to_database.setText(_translate("MainMenu", "Добавить новый элемент в базу"))
        self.update_database.setText(_translate("MainMenu", "Обновить элемент в базе"))
        self.delete_element_of_database.setText(_translate("MainMenu", "Удалить элемент из базы"))
        self.exit_application.setText(_translate("MainMenu", "Выход"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainMenu = QtWidgets.QMainWindow()
#     ui = Ui_MainMenu()
#     ui.setupUi(MainMenu)
#     MainMenu.show()
#     sys.exit(app.exec_())
